# frontend/Dockerfile.prod

FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_VAPID_PUBLIC_KEY

COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .

RUN echo "--- DEBUG: VAPID Key received by build process: $VITE_VAPID_PUBLIC_KEY ---" && \
    VITE_VAPID_PUBLIC_KEY=$VITE_VAPID_PUBLIC_KEY npm run build

FROM nginx:alpine
COPY frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]